#!/usr/bin/env python
#--------------------
""" Created on 2019-01-24 by Mikhail Dubrovin
    2020-03-12 add parameter --rot to account for location of the Q0 in optical measurements.
               expected detector orientation with Q0 in upper-left corner is shown on photo
               Confluence PSDM EPIX10KA2M and EPIX10KAQUAD - Metrology map from ChrisKenney
               Metrology from 2020-02-25 was done with Q0 in the lower-left corner...
    2020-08-12 add parameter --vers to generate constants without quads for uniform detector.
"""

from CalibManager.OpticAlignmentUtils import OpticalMetrologyEpix10ka2M

import os
import sys
import logging
logger = logging.getLogger(__name__)

DICT_NAME_TO_LEVEL = {k:v for k,v in logging._levelNames.iteritems() if isinstance(k, str)}
LEVEL_NAMES = ', '.join(DICT_NAME_TO_LEVEL.keys())
#LEVEL_NAMES = ', '.join(list(logging._levelToName.values())) # PYTHON 3

#--------------------

def usage():
    return '\nCommand to run:'+\
           '\n  %prog'+\
           ' -i <input-file-name> -o <output-file-name> ...'+\
           '\n\n  Example:'+\
           '\n      %prog -i optical-metrology.txt -o results/optmet-2019-01-24'+\
           '\n      %prog -i optical-metrology.txt -r 3 -o results/optmet-2020-02-25'+\
           '\n  Alternative:'+\
           '\n      %prog optical-metrology.txt'

#--------------------

def option_parser():

    from optparse import OptionParser

    d_ifn = './optical_metrology.txt'
    d_ofn = './geometry-epix10ka2m.txt' 
    d_log = 'DEBUG'
    d_xc  = 78000
    d_yc  = -4150
    d_rot = 0
    d_vers= 1
  
    h_ifn = 'input file name, default = %s' % d_ifn
    h_ofn = 'output file(s) name, default = %s' % d_ofn 
    h_log = 'logging level from list (%s), default = %s' % (LEVEL_NAMES, d_log)
    h_xc  = 'x coordinate [um] of camera center in optical frame, default = %d' % d_xc
    h_yc  = 'y coordinate [um] of camera center in optical frame, default = %d' % d_yc
    h_rot = 'detector rotation in optical metrology: 0-Q0 upper-left, 3-Q0 down-left , default = %s' % d_rot
    h_vers= 'processor version = 0-quads, 1-monolitic, default = %s' % d_vers
  
    parser = OptionParser(description='Optical metrology processing for Epix10ka2M', usage=usage())
    parser.add_option('-i', '--ifn', default=d_ifn, action='store', type='string', help=h_ifn)
    parser.add_option('-o', '--ofn', default=d_ofn, action='store', type='string', help=h_ofn)
    parser.add_option('-l', '--log', default=d_log, action='store', type='string', help=h_log)
    parser.add_option('-x', '--xc',  default=d_xc,  action='store', type='int',    help=h_xc)
    parser.add_option('-y', '--yc',  default=d_yc,  action='store', type='int',    help=h_yc)
    parser.add_option('-r', '--rot', default=d_rot, action='store', type='int',    help=h_rot)
    parser.add_option('-v', '--vers',default=d_vers,action='store', type='int',    help=h_vers)

    return parser

#--------------------

def proc_optical_metrology_epix10ka2m():
    parser = option_parser()
    (popts, pargs) = parser.parse_args()
    print('optional loglevel: %s' % popts.log)

    int_level=DICT_NAME_TO_LEVEL[popts.log]
    logging.basicConfig(format='[%(levelname).1s] L%(lineno)04d: %(message)s', level=int_level)
    #logger.setLevel(int_level)
    #logger.debug('logger.level %d: %s' % (logger.level, logging.getLevelName(logger.level)))

    OpticalMetrologyEpix10ka2M(parser)

#--------------------

if __name__ == '__main__':
    proc_optical_metrology_epix10ka2m()
    sys.exit()

#--------------------
